apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  namespace: dev
data:
  APP_NAME: "Laravel Notes"
  APP_ENV: "dev"
  APP_DEBUG: "true"
  APP_URL: "http://localhost"

  LOG_CHANNEL: "stack"
  LOG_LEVEL: "debug"

  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "notes_db"
  DB_USERNAME: "laravel_user"

  CACHE_STORE: "redis"
  QUEUE_CONNECTION: "redis"
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
