apiVersion: v1
kind: Service
metadata:
  name: laravel-nginx
  namespace: dev
spec:
  selector:
    app: laravel-stack
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
